CREATE TABLE IF NOT EXISTS `cdr` (
  `uuid` varchar(100) NOT NULL,
  `acctcode` varchar(100) NOT NULL,
  `ani` varchar(100) NOT NULL,
  `e164_ani` varchar(100) NOT NULL,
  `dnis` varchar(100) NOT NULL,
  `e164_dnis` varchar(100) NOT NULL,
  `translated_dnis` varchar(100) NOT NULL,
  `src_host` varchar(100) NOT NULL,
  `read_codec` varchar(100) NOT NULL,
  `write_codec` varchar(100) NOT NULL,
  `clid_name` varchar(100) NOT NULL,
  `clid_number` varchar(100) NOT NULL,
  `src_sdp` varchar(100) NOT NULL,
  `dest_sdp` varchar(100) NOT NULL,
  `originate_disposition` varchar(100) NOT NULL,
  `bridge_to_uuid` varchar(100) NOT NULL,
  `endpoint_disposition` varchar(100) NOT NULL,
  `sip_hangup_disposition` varchar(100) NOT NULL,
  `term_cause` varchar(100) NOT NULL,
  `hangup_cause` varchar(100) NOT NULL,
  `start_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `answer_stamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `progress_media_stamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_stamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `duration` int(11) NOT NULL,
  `billsec` int(11) NOT NULL,
  `progress_mediasec` int(11) NOT NULL,
  `billmin` varchar(100) NOT NULL,
  `carrier_id` varchar(100) NOT NULL,
  `cust_cost` varchar(100) NOT NULL,
  `carrier_cost` varchar(100) NOT NULL
)
