# makefile

all:

install:
	install -d $(DESTDIR)/usr/share/freeswitch/htdocs
	install -m0644 slimtest.htm $(DESTDIR)/usr/share/freeswitch/htdocs/slimtest.htm
	install -m0644 xspf_player_slim.swf $(DESTDIR)/usr/share/freeswitch/htdocs/slim.swf

clean:

