<?php
$ERRMSG[KICK_SUCCESS] = "Éxito: kick";
$ERRMSG[KICK_FAIL]    = "Fall: kick";
$ERRMSG[MUTE_SUCCESS] = "Éxito: mute";
$ERRMSG[MUTE_FAIL]    = "Fall: mute";
$ERRMSG[UNMUTE_SUCCESS] = "Éxito: unmute";
$ERRMSG[UNMUTE_FAIL]    = "Fall: unmute";
$ERRMSG[DEAF_SUCCESS] = "Éxito: deaf";
$ERRMSG[DEAF_FAIL]    = "Fall: deaf";
$ERRMSG[UNDEAF_SUCCESS] = "Éxito: undeaf";
$ERRMSG[UNDEAF_FAIL]    = "Fall: undeaf";
?>
