<?php
$ERRMSG[KICK_SUCCESS] = "Success: kick";
$ERRMSG[KICK_FAIL]    = "Fail: kick";
$ERRMSG[MUTE_SUCCESS] = "Success: mute";
$ERRMSG[MUTE_FAIL]    = "Fail: mute";
$ERRMSG[UNMUTE_SUCCESS] = "Success: unmute";
$ERRMSG[UNMUTE_FAIL]    = "Fail: unmute";
$ERRMSG[DEAF_SUCCESS] = "Success: deaf";
$ERRMSG[DEAF_FAIL]    = "Fail: deaf";
$ERRMSG[UNDEAF_SUCCESS] = "Success: undeaf";
$ERRMSG[UNDEAF_FAIL]    = "Fail: undeaf";
?>