#ifndef KGSM_H
#define KGSM_H

/*
 * KGsmCallCause: Causes for Call Fail
 */
enum KGsmCallCause
{
    kgccNone                      = 0,
    kgccUnallocatedNumber         = 1,
    kgccNoRouteToDest             = 3,
    kgccChannelUnacceptable       = 6,
    kgccOperatorDeterminedBarring = 8,
    kgccNormalCallClear           = 16,
    kgccUserBusy                  = 17,
    kgccNoUserResponding          = 18,
    kgccNoAnswerFromUser          = 19,
    kgccCallRejected              = 21,
    kgccNumberChanged             = 22,
    kgccNonSelectedUserClear      = 26,
    kgccDestinationOutOfOrder     = 27,
    kgccInvalidNumberFormat       = 28,
    kgccFacilityRejected          = 29,
    kgccRespStatusEnquiry         = 30,
    kgccNormalUnspecified         = 31,
    kgccNoCircuitChannelAvail     = 34,
    kgccNetworkOutOfOrder         = 38,
    kgccTemporaryFailure          = 41,
    kgccSwitchCongestion          = 42,
    kgccAccessInfoDiscarded       = 43,
    kgccRequestedChannelUnav      = 44,
    kgccResourceUnavailable       = 47,
    kgccQosUnavailable            = 49,
    kgccReqFacilityNotSubsc       = 50,
    kgccCallBarredWitchCUG        = 55,
    kgccBearerCapabNotAuthor      = 57,
    kgccBearerCapabNotAvail       = 58,
    kgccServiceNotAvailable       = 63,
    kgccBcNotImplemented          = 65,
    kgccReqFacilityNotImplem      = 69,
    kgccOnlyRestrictedBcAvail     = 70,
    kgccServiceNotImplemented     = 79,
    kgccInvalidCrv                = 81,
    kgccUserNotMemberOfCUG        = 82,
    kgccIncompatibleDestination   = 88,
    kgccInvalidTransitNetSel      = 91,
    kgccInvalidMessage            = 95,
    kgccMissingMandatoryIe        = 96,
    kgccMsgTypeNotImplemented     = 97,
    kgccMsgIncompatWithState      = 98,
    kgccIeNotImplemented          = 99,
    kgccInvalidIe                 = 100,
    kgccMsgIncompatWithState2     = 101,
    kgccRecoveryOnTimerExpiry     = 102,
    kgccProtocolError             = 111,
    kgccInterworking              = 127,
};

/*
 *  KGsmMobileCause: Causes of Mobile Equipment Fail
 */
enum KGsmMobileCause
{
    kgmcPhoneFailure                = 0,
    kgmcNoConnectionToPhone         = 1,
    kgmcPhoneAdaptorLinkReserved    = 2,
    kgmcOperationNotAllowed         = 3,
    kgmcOperationNotSupported       = 4,
    kgmcPH_SIMPINRequired           = 5,
    kgmcPH_FSIMPINRequired          = 6,
    kgmcPH_FSIMPUKRequired          = 7,
    kgmcSIMNotInserted              = 10,
    kgmcSIMPINRequired              = 11,
    kgmcSIMPUKRequired              = 12,
    kgmcSIMFailure                  = 13,
    kgmcSIMBusy                     = 14,
    kgmcSIMWrong                    = 15,
    kgmcIncorrectPassword           = 16,
    kgmcSIMPIN2Required             = 17,
    kgmcSIMPUK2Required             = 18,
    kgmcMemoryFull                  = 20,
    kgmcInvalidIndex                = 21,
    kgmcNotFound                    = 22,
    kgmcMemoryFailure               = 23,
    kgmcTextStringTooLong           = 24,
    kgmcInvalidCharInTextString     = 25,
    kgmcDialStringTooLong           = 26,
    kgmcInvalidCharInDialString     = 27,
    kgmcNoNetworkService            = 30,  
    kgmcNetworkTimeout              = 31,  
    kgmcNetworkNotAllowed           = 32,
    kgmcCommandAborted              = 33,
    kgmcNumParamInsteadTextParam    = 34,
    kgmcTextParamInsteadNumParam    = 35,
    kgmcNumericParamOutOfBounds     = 36,
    kgmcTextStringTooShort          = 37,
    kgmcNetworkPINRequired          = 40,
    kgmcNetworkPUKRequired          = 41,
    kgmcNetworkSubsetPINRequired    = 42,
    kgmcNetworkSubnetPUKRequired    = 43,
    kgmcServiceProviderPINRequired  = 44,
    kgmcServiceProviderPUKRequired  = 45,
    kgmcCorporatePINRequired        = 46,
    kgmcCorporatePUKRequired        = 47,
    kgmcSIMServiceOptNotSupported   = 60,
    kgmcUnknown                     = 100,
    kgmcIllegalMS_N3                = 103,
    kgmcIllegalME_N6                = 106,
    kgmcGPRSServicesNotAllowed_N7   = 107,
    kgmcPLMNNotAllowed_No11         = 111,
    kgmcLocationAreaNotAllowed_N12  = 112,
    kgmcRoamingNotAllowed_N13       = 113,
    kgmcServiceOptNotSupported_N32  = 132,
    kgmcReqServOptNotSubscribed_N33 = 133,
    kgmcServOptTempOutOfOrder_N34   = 134,
    kgmcLongContextActivation       = 147,
    kgmcUnspecifiedGPRSError        = 148,
    kgmcPDPAuthenticationFailure    = 149,
    kgmcInvalidMobileClass          = 150,
    kgmcGPRSDisconnectionTmrActive  = 151,
    kgmcTooManyActiveCalls          = 256,
    kgmcCallRejected                = 257,
    kgmcUnansweredCallPending       = 258,
    kgmcUnknownCallingError         = 259,
    kgmcNoPhoneNumRecognized        = 260,
    kgmcCallStateNotIdle            = 261,
    kgmcCallInProgress              = 262,
    kgmcDialStateError              = 263,
    kgmcUnlockCodeRequired          = 264,
    kgmcNetworkBusy                 = 265,
    kgmcInvalidPhoneNumber          = 266,
    kgmcNumberEntryAlreadyStarted   = 267,
    kgmcCancelledByUser             = 268,
    kgmcNumEntryCouldNotBeStarted   = 269,
    kgmcDataLost                    = 280,
    kgmcInvalidBessageBodyLength    = 281,
    kgmcInactiveSocket              = 282,
    kgmcSocketAlreadyOpen           = 283
};

/*
 *  KGsmSmsCause: Causes of SMS Fail
 */
enum KGsmSmsCause
{
    kgscUnassigned                  = 1,
    kgscOperatorDeterminedBarring   = 8,
    kgscCallBarred                  = 10,
    kgscSMSTransferRejected         = 21,
    kgscDestinationOutOfService     = 27,
    kgscUnidentifiedSubscriber      = 28,
    kgscFacilityRejected            = 29,
    kgscUnknownSubscriber           = 30,
    kgscNetworkOutOfOrder           = 38,
    kgscTemporaryFailure            = 41,
    kgscCongestion                  = 42,
    kgscResourcesUnavailable        = 47,
    kgscFacilityNotSubscribed       = 50,
    kgscFacilityNotImplemented      = 69,
    kgscInvalidSMSTransferRefValue  = 81,
    kgscInvalidMessage              = 95,
    kgscInvalidMandatoryInformation = 96,
    kgscMessageTypeNonExistent      = 97,
    kgscMsgNotCompatWithSMProtState = 98,
    kgscInformationElementNonExiste = 99,
    kgscProtocolError               = 111,
    kgscInterworking                = 127,
    kgscTelematicInterworkingNotSup = 128,
    kgscSMSTypeZeroNotSupported     = 129,
    kgscCannotReplaceSMS            = 130,
    kgscUnspecifiedTPPIDError       = 143,
    kgscAlphabetNotSupported        = 144,
    kgscMessageClassNotSupported    = 145,
    kgscUnspecifiedTPDCSError       = 159,
    kgscCommandCannotBeActioned     = 160,
    kgscCommandUnsupported          = 161,
    kgscUnspecifiedTPCommandError   = 175,
    kgscTPDUNotSupported            = 176,
    kgscSCBusy                      = 192,
    kgscNoSCSubscription            = 193,
    kgscSCSystemFailure             = 194,
    kgscInvalidSMEAddress           = 195,
    kgscDestinationSMEBarred        = 196,
    kgscSMRejectedDuplicateSM       = 197,
    kgscTPVPFNotSupported           = 198,
    kgscTPVPNotSupported            = 199,
    kgscSIMSMSStorageFull           = 208,
    kgscNoSMSStorageCapabilityInSIM = 209,
    kgscErrorInMS                   = 210,
    kgscMemoryCapacityExceeded      = 211,
    kgscSIMDataDownloadError        = 213,
    kgscUnspecifiedError            = 255,
    kgscPhoneFailure                = 300,
    kgscSmsServiceReserved          = 301,
    kgscOperationNotAllowed         = 302,
    kgscOperationNotSupported       = 303,
    kgscInvalidPDUModeParameter     = 304,
    kgscInvalidTextModeParameter    = 305,
    kgscSIMNotInserted              = 310,
    kgscSIMPINNecessary             = 311,
    kgscPH_SIMPINNecessary          = 312,
    kgscSIMFailure                  = 313,
    kgscSIMBusy                     = 314,
    kgscSIMWrong                    = 315,
    kgscMemoryFailure               = 320,
    kgscInvalidMemoryIndex          = 321,
    kgscMemoryFull                  = 322,
    kgscSMSCAddressUnknown          = 330,
    kgscNoNetworkService            = 331,
    kgscNetworkTimeout              = 332,
    kgscUnknownError                = 500,
    kgscNetworkBusy                 = 512,
    kgscInvalidDestinationAddress   = 513,
    kgscInvalidMessageBodyLength    = 514,
    kgscPhoneIsNotInService         = 515,
    kgscInvalidPreferredMemStorage  = 516,
    kgscUserTerminated              = 517
};

#endif
